### ISSUE TITLE
Job Status window will not open on NRC workstation, incomplete on RESGC (SNAP 4.0.2)

### ISSUE THREAD

**Issue by AndrewIrelandNRC** [NRC-Research/SNAP-issues#28]
Job streams can be successfully submitted and run, but the Job Status window cannot be viewed. Does not launch automatically when job is submitted, won't open from the SNAP menu "Tools > Job Stream", or from windows menu item.

js.screen has the following:

```
Symbolic Nuclear Analysis Package, Version 4.0.2, January 21, 2022
Windows 8 6.2 (amd64)
International Business Machines Corporation Eclipse OpenJ9 VM 11.0.12 (64-bit)
[Mon Apr 11 10:23:28 EDT 2022] ProviderFactory.DEBUG: Using SNAP Azure OIDC credentials provider.
java.lang.NullPointerException
	at com.cafean.client.ui.ApplicationFrame.addMessage(ApplicationFrame.java:3814)
	at com.cafean.client.ui.message.Message.addMessage(Message.java:477)
	at com.cafean.client.ui.message.Message.addMessage(Message.java:356)
	at com.cafean.jobstream.client.util.MessageWindowProgress.failure(MessageWindowProgress.java:38)
	at Job Status FileAccessors//com.cafean.jobstream.aws.accessor.S3FileAccessor.getFile(S3FileAccessor.java:125)
	at com.cafean.jobstream.client.io.JobStatusSiteConfigLoader.getGlobalConfigFromURI(JobStatusSiteConfigLoader.java:86)
	at com.cafean.config.site.AbstractSiteConfigLoader.findGlobalConfig(AbstractSiteConfigLoader.java:204)
	at com.cafean.config.site.AbstractSiteConfigLoader.readGlobalConfig(AbstractSiteConfigLoader.java:324)
	at com.cafean.config.site.AbstractSiteConfigLoader.initialize(AbstractSiteConfigLoader.java:114)
	at com.cafean.JobStatus.Main.main(Main.java:402)
	at JobStatus.main(JobStatus.java:18)
```

On RESGC, Job Status opens, but looks like this. (Same js.screen message as on the NRC workstation.)

![image](https://user-images.githubusercontent.com/87270563/162770707-ed269338-a45a-4b7f-be3c-a88bb09276cc.png)

**Comment by dul-apt** [comment]
This issue will be resolved in the SNAP 4.0.3 release and is described in issue https://github.com/NRC-Research/SNAP-issues/issues/23
